[profile.default]
solc = "0.8.20"
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
optimizer = false

[profile.production]
optimizer = true

[fmt]
tab_width = 2
number_underscore = 'thousands'
